name: First deploy CI/CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-project:
    runs-on: ubuntu-latest

    steps:
      - name: Скачиваем репозиторий
        uses: actions/checkout@v4

      - name: Установка Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26'

      - name: Компиляция кода
        run: go build -v ./...

      - name: ШПИОН - Проверка видимости секретов
        run: |
          if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then echo "❌ ОШИБКА: Логин ПУСТОЙ (Гитхаб не видит секрет)"; else echo "✅ Логин НАЙДЕН в сейфе"; fi
          if [ -z "${{ secrets.DOCKER_TOKEN }}" ]; then echo "❌ ОШИБКА: Токен ПУСТОЙ (Гитхаб не видит секрет)"; else echo "✅ Токен НАЙДЕН в сейфе"; fi

      - name: Авторизация Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Сборка Docker образа
        run: docker build -t my-go-app:latest .

      - name: Настройка Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: СБорка и пуш Docker
        uses: docker/buildx-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/my-go-app:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
